# Working with ndarrays

In [181]:
# Is  a (usually fixed-size) multidimensional 
# container of items of the same type and size.

In [204]:
import numpy as np

# creates a 2 x 3 (2 rows, 3 columns) 2D array of int32s
# without np.int32, defaults to int64 data type
x = np.array([[1,2,3], [4,5,6]], np.int32)
"""
[1,2,3]
[4,5,6]

TODO: So it appears to be nested lists within a list?

"""

# object type is numpy.ndarray
type(x)

numpy.ndarray

In [205]:
# shape is 2 x 3 (2 rows, 3 columns)
x.shape

(2, 3)

In [206]:
# data type is int32
x.dtype

dtype('int32')

In [207]:
# access element [row, column] 
# 1th row, 2th column
x[1,2]

6

#### learn slicing first

In [208]:
# Slicing - [start index included:stop index excluded: step] where
# step is number of hops from included start index
y = np.array([0,1,2,3,4,5,6,7,8,9])
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
# include 0th, exclude 9th, step every two
y[0:9:2]

array([0, 2, 4, 6, 8])

In [192]:
# negative indexes from the right (but as if an imaginary one
# hanging out there)
y[-10:9:2]

array([0, 2, 4, 6, 8])

In [193]:
# if start (included) is to right of stop (excluded), step
# must be negative, moving from start
y[-3:3:-1]

array([7, 6, 5, 4])

#### back to ndarray

In [209]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [215]:
# slicing an ndarray
# in this case, [I slice rows:I AM the included column]
z = x[:,1]
z

array([2, 5], dtype=int32)

In [217]:
# slice the first 2x2
z3 = x[:2,:2]
z3

array([[1, 2],
       [4, 5]], dtype=int32)

In [220]:
# objects are passed by reference, so original is changed
z[0] = 9 # changes the 0th item in the z variable
z

array([9, 5], dtype=int32)

In [221]:
# the slice from x was changed so original is now changed
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)