# NumPy Quickstart Tutorial
From NumPy's '[Quickstart Tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)':

"NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes(pl). The number of *axes* is referred to as *rank*."

Basically, NumPy's ndarray is a list of lists with dimensionality and other features.

In [1]:
import numpy as np

In [2]:
# note, arrange(n) returns an evenly spaced ndarray from 0 to n
# reshape(n,m) defines the shape dimensions. Product must be n
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# show shape (n, m) where n = number of rows and m = number of columns
a.shape

(3, 5)

In [4]:
# show number of dimensions (ex, 2D, 3D, etc.)
a.ndim

2

In [5]:
# creates a new 1D ndarray via arange(n) and reshape(n)
a_1d = np.arange(15).reshape(15)
a_1d.ndim

1

In [6]:
# show datatype
a.dtype.name

'int64'

In [7]:
# Length of one array element in bytes.
a.itemsize

8

In [8]:
# number of items in ndarray
a.size

15

In [9]:
# type
type(a)

numpy.ndarray

In [10]:
# my original ndarray
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
# a new ndarray called 'b'
b = np.array([6,7,8])
b

array([6, 7, 8])

In [12]:
# b is of type ndarray just like a
type(b)

numpy.ndarray

In [13]:
# notice making 2x3 ndarray with two lists within a list
b_l = np.array([[1,2,3],[4,5,6]])
b_l

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# same thing as b_1 ndarray but using a list of tuples
# result is same as above
b_t = np.array([(1,2,3),(4,5,6)])
b_t

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# can specify the data type of the contents of the array
# here I made it float64 type
c = np.array([[1,2],[3,4]], dtype='float64')
c

array([[ 1.,  2.],
       [ 3.,  4.]])

In [16]:
# 3x4 ndarray full of zeros forced to be int (is float by default)
np.zeros((3,4), dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
# same as above but with default datatype float
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
# output datatype of same array
np.zeros((3,4)).dtype.name

'float64'

In [19]:
# a 3D ndarray, 2x3x4 full of ones of type int16
# is essentially two 3x4 arrays (lists within lists within a list)
# using datatype 'np.int16' here as more explicit version of int16 in NumPy
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
# arange() function where (start inclusive, stop exclusive, step)
# remeber, arange() retruns an ndarray
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
# create a 2x4 array with two of the same ndarrays
np.array((np.arange(10,30,5),(np.arange(10,30,5))))

array([[10, 15, 20, 25],
       [10, 15, 20, 25]])

In [22]:
# can use floats with arange() but difficult to predict
# how many you'll end up with (math)
# in this case I get five values. Six values would take me out of range to 2.004
np.arange(0,2,0.334)

array([ 0.   ,  0.334,  0.668,  1.002,  1.336,  1.67 ])

In [23]:
# if want to explicitly state many numbers will generate, 
# better to use linspace()
np.linspace(0,1.5,4) 
# 4 numbers between 0 and 1.5. Note that 1.5 is inclusive

array([ 0. ,  0.5,  1. ,  1.5])

In [24]:
# use an ndarray as input to take the sin of each value in the array
x = np.linspace(0,1.5,4)
f = np.sin(x)
f

array([ 0.        ,  0.47942554,  0.84147098,  0.99749499])

In [25]:
# note, NumPy uses elipses when printing large sets
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]
