# Working with ndarrays

In [2]:
import numpy as np

# creates a 2 x 3 (2 rows, 3 columns) 2D array of int32s
# without np.int32, defaults to int64 data type
jjj
"""
[1,2,3]
[4,5,6]

TODO: So it appears to be nested lists within a list?

"""

# object type is numpy.ndarray
type(x)

numpy.ndarray

In [3]:
# shape is 2 x 3 (2 rows, 3 columns)
x.shape

(2, 3)

In [4]:
# data type is int32
x.dtype

dtype('int32')

In [5]:
# access element [row, column] 
# 1th row, 2th column
x[1,2]

6

##### learn slicing first

In [6]:
jj

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
j~

array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

In [9]:
j

array([7, 6, 5, 4])

##### back to ndarray

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [11]:
j

array([2, 5], dtype=int32)

array([[1, 2],
       [4, 5]], dtype=int32)

array([9, 5], dtype=int32)

In [14]:
# the slice from x was changed so original is now changed
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)