# NumPy Quickstart Tutorial
From NumPy's '[Quickstart Tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)':

"NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes(pl). The number of *axes* is referred to as *rank*."

Basically, NumPy's ndarray is a list of lists with dimensionality and other features.

### Making ndarrays

In [2]:
# import numpy
import numpy as np

In [4]:
# create ndarray from 0 to 14
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# define an ndarray as multidimensional
# reshape(n,m) defines the shape dimensions. Product must be equal to number of things in array
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
# return shape (n, m) where n = number of rows and m = number of columns
a.shape

(3, 5)

In [13]:
# return number of dimensions (ex, 2D, 3D, etc.)
a.ndim

2

In [14]:
# return datatype
a.dtype.name

'int64'

In [15]:
# return length of one array element in bytes
a.itemsize

8

In [16]:
# return number of items in ndarray
a.size

15

In [11]:
# make an ndarray using a python list
b = np.array([6,7,8])
b

array([6, 7, 8])

In [17]:
# make a multidimensional ndarray using a list of lists
b_l = np.array([[1,2,3],[4,5,6]])
b_l

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# same thing but using tuples
b_t = np.array([(1,2,3),(4,5,6)])
b_t

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# specify the data type of the contents of the array
c = np.array([[1,2],[3,4]], dtype='float64')
c

array([[ 1.,  2.],
       [ 3.,  4.]])

In [29]:
# make 3x4 ndarray full of zeros forced to be int 
np.zeros((3,4), dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
# same as above but with default datatype float 
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [31]:
# output datatype as a string
np.zeros((3,4)).dtype.name

'float64'

In [32]:
# make a 3D ndarray, 2x3x4 full of ones of type int16
# is essentially two 3x4 arrays (lists within lists within a list)
# using datatype 'np.int16' here as more explicit version of int16 in NumPy
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
# make ndarray using arange() function (start inclusive, stop exclusive, step)
np.arange(10,30,5)

array([10, 15, 20, 25])

In [34]:
# make a 2x4 array with arange()
np.array((np.arange(10,30,5),(np.arange(10,30,5))))

array([[10, 15, 20, 25],
       [10, 15, 20, 25]])

In [27]:
# make ndarray with arange() and floats
# can use floats with arange() but difficult to predict
# how many you'll end up with (math)
# in this case I get five values. Six values would take me out of range to 2.004
np.arange(0,2,0.334)

array([ 0.   ,  0.334,  0.668,  1.002,  1.336,  1.67 ])

In [22]:
# make ndarray with explicit number of numbers using linspace()
# 4 numbers between 0 and 1.5. Note that 1.5 is inclusive
np.linspace(0,1.5,4) 

array([ 0. ,  0.5,  1. ,  1.5])

In [38]:
# take sin of each value in array
x = np.linspace(0,1.5,4)
f = np.sin(x)
f

array([ 0.        ,  0.47942554,  0.84147098,  0.99749499])

In [39]:
# note, NumPy uses elipses when printing large sets
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


### Slicing ndarrays

In [40]:
# make an array
y = np.array([0,1,2,3,4,5,6,7,8,9])
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# slice: include 0th, exclude 9th, step every two
y[0:9:2]

array([0, 2, 4, 6, 8])

In [42]:
# slice with negative indices - from the right (but as if an imaginary one hanging out there)
y[-10:9:2]

array([0, 2, 4, 6, 8])

In [43]:
# slice - if start (included) is to right of stop (excluded), step
# must be negative, moving from start
y[-3:3:-1]

array([7, 6, 5, 4])

In [45]:
# create a new 2D ndarray
x = np.array([[1,2,3], [4,5,6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [46]:
# slice a 2D ndarray
# in this case, [I slice rows:I AM the included column]
z = x[:,1]
z

array([2, 5], dtype=int32)

In [47]:
# slice the first 2x2
z3 = x[:2,:2]
z3

array([[1, 2],
       [4, 5]], dtype=int32)

In [49]:
# show z again
z

array([2, 5], dtype=int32)

In [50]:
# objects are passed by reference, so original is changed
z[0] = 9 # changes the 0th item in the z variable
z

array([9, 5], dtype=int32)

In [51]:
# the slice, z, was from x, so original is now changed
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [52]:
# access element [row, column] 
# 1th row, 2th column
x[1,2]

6

### Pass by Reference vs. Pass by Value

##### Pass by Reference

In [10]:
# create an ndarray
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
# now create a new reference to a called b
b = a
b

array([1, 2, 3, 4])

In [12]:
# modify in place addition of another ndarray
a += np.array([1,1,1,1])
a

array([2, 3, 4, 5])

In [13]:
# notice b has changed though operation only carried out on a
b

array([2, 3, 4, 5])

##### Pass by Value

In [15]:
# create another ndarray
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [17]:
# again create a new reference to a called b
b = a
b

array([1, 2, 3, 4])

In [18]:
# modify the a without changing the reference
a = a + np.array([1,1,1,1])
a

array([2, 3, 4, 5])

In [19]:
# b is unchanged
b

array([1, 2, 3, 4])